# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e435bdd4c1499aa280b5163f1feece03b4dfe4b48becd5903862890a2bd1678c7b28e4f6a602514dd37a3f43d82f28b7ef52cc686c1e8a708426a40f52a21bb

test:
  secret_key_base: 7c5ef9bdb4ffb5cd38c4213052a42e03a368eb9bf701c327ec50526cc0d7e0aadd7f200e3ccec12d4b45423c1205da862d5c566c7928430c5a476653fda6e591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
